### ISSUE TITLE
[IncreaseDroprate] Equipment drop rates don't match vanilla with suggested settings

### ISSUE THREAD

**Issue by JL2210** [olegbl/d2rmm.mods#7]
I dug into the itemratio.txt a little bit before and after installing the mod and noticed that the numbers on some of the rows were different with the "vanilla" settings, as it does not take into account differences between LoD/Classic or class-specific items. I made a modification that rectifies this issue on my end while not breaking existing configuration; unfortunately, I can't send a patch, as I'm on Windows right now. Here's the full file:
[IncreaseDroprateEdit.zip](https://github.com/olegbl/d2rmm.mods/files/11777710/IncreaseDroprateEdit.zip)

**Comment by olegbl** [comment]
Yes, the vanilla values are only approximations and are only valid for standard items. However, if I modify the formula (e.g. as in your version), then the percentages are no longer accurate (i.e. putting in 1 would not get you an approximately 1% drop rate) for Uber or class specific items.

The early versions of this mod (e.g. 1.0) allowed you to modify the values in a more deterministic way and get actual vanilla values, but people found it very confusing (D2's drop rate formula _is_ pretty confusing), hence I change it to use percentages in order to make the mod simpler to configure.

If you would like to have an alternative formula, you can use an old version of this mod, or use your own modification (or publish it at a standalone mod), but I do not think I'm going to go back on this trade off.
