### ISSUE TITLE
Town Cast - battle orders only works on player

### ISSUE THREAD

**Issue by Caedendi** [olegbl/d2rmm.mods#8]
Hi, idk if you've noticed this before but aoe buffing in town only works for the player. Is it something that can be fixed? If no, why?
It's not that big of a deal cuz you can still buff outside of town and I mainly use it for teleporting in town anyways.

**Comment by olegbl** [comment]
Sorry, not sure about that. The mod just sets the `InTown` column for each of these spells to `1` (instead of the default `0`). I am unsure if D2R has further restrictions on _how_ those spells work in town. It may be something like the allies not being targetable while in town and thus being unable to receive the buff. I am unsure.
